// To regenerate api.pb.go run `hack/update-codegen.sh protobindings`

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: sandbox.proto

package apis

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PodID is the UUID of the pod for which devices are being sought
	PodID string `protobuf:"bytes,1,opt,name=PodID,proto3" json:"PodID,omitempty"`
	// Count is the number of devices needed
	Count int32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	// DeviceType is the type of device
	DeviceType    string `protobuf:"bytes,3,opt,name=DeviceType,proto3" json:"DeviceType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceRequest) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

func (x *DeviceRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DeviceRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type PhysicalDeviceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PhysicalDeviceID is the list of physical ids of the devices requested
	PhysicalDeviceID []string `protobuf:"bytes,1,rep,name=PhysicalDeviceID,proto3" json:"PhysicalDeviceID,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhysicalDeviceResponse) Reset() {
	*x = PhysicalDeviceResponse{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalDeviceResponse) ProtoMessage() {}

func (x *PhysicalDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalDeviceResponse.ProtoReflect.Descriptor instead.
func (*PhysicalDeviceResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *PhysicalDeviceResponse) GetPhysicalDeviceID() []string {
	if x != nil {
		return x.PhysicalDeviceID
	}
	return nil
}

type AllocateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PodID is the uuid string of the pod
	PodID string `protobuf:"bytes,1,opt,name=PodID,proto3" json:"PodID,omitempty"`
	// ContainerID is the uuid string of a container within the pod
	ContainerID string `protobuf:"bytes,2,opt,name=ContainerID,proto3" json:"ContainerID,omitempty"`
	// VirtualDeviceID is a list of virtual_ids that should be associated with the pod
	VirtualDeviceID []string `protobuf:"bytes,3,rep,name=VirtualDeviceID,proto3" json:"VirtualDeviceID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateRequest) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

func (x *AllocateRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *AllocateRequest) GetVirtualDeviceID() []string {
	if x != nil {
		return x.VirtualDeviceID
	}
	return nil
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\x04apis\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\"[\n" +
	"\rDeviceRequest\x12\x14\n" +
	"\x05PodID\x18\x01 \x01(\tR\x05PodID\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x05R\x05Count\x12\x1e\n" +
	"\n" +
	"DeviceType\x18\x03 \x01(\tR\n" +
	"DeviceType\"D\n" +
	"\x16PhysicalDeviceResponse\x12*\n" +
	"\x10PhysicalDeviceID\x18\x01 \x03(\tR\x10PhysicalDeviceID\"s\n" +
	"\x0fAllocateRequest\x12\x14\n" +
	"\x05PodID\x18\x01 \x01(\tR\x05PodID\x12 \n" +
	"\vContainerID\x18\x02 \x01(\tR\vContainerID\x12(\n" +
	"\x0fVirtualDeviceID\x18\x03 \x03(\tR\x0fVirtualDeviceID2\x98\x01\n" +
	"\aSandbox\x12J\n" +
	"\x13GetDeviceAllocation\x12\x13.apis.DeviceRequest\x1a\x1c.apis.PhysicalDeviceResponse\"\x00\x12A\n" +
	"\bAllocate\x12\x15.apis.AllocateRequest\x1a\x1c.apis.PhysicalDeviceResponse\"\x00BO\xc8\xe1\x1e\x01\xd8\xe1\x1e\x00\x80\xe2\x1e\x01\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\xe0\xe2\x1e\x01\x90\xe3\x1e\x00Z1github.com/NVIDIA/sandbox-device-plugin/pkg/apis/b\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sandbox_proto_goTypes = []any{
	(*DeviceRequest)(nil),          // 0: apis.DeviceRequest
	(*PhysicalDeviceResponse)(nil), // 1: apis.PhysicalDeviceResponse
	(*AllocateRequest)(nil),        // 2: apis.AllocateRequest
}
var file_sandbox_proto_depIdxs = []int32{
	0, // 0: apis.Sandbox.GetDeviceAllocation:input_type -> apis.DeviceRequest
	2, // 1: apis.Sandbox.Allocate:input_type -> apis.AllocateRequest
	1, // 2: apis.Sandbox.GetDeviceAllocation:output_type -> apis.PhysicalDeviceResponse
	1, // 3: apis.Sandbox.Allocate:output_type -> apis.PhysicalDeviceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
